services:
  - type: web
    name: staynJoy-backend
    runtime: java
    buildCommand: cd Back-End/Back-End && chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar Back-End/Back-End/target/Back-End-0.0.1-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://staynjoy.scriptbliss.com
